{
 "title": "Different Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "hit_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Histogram Metric",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "email_time_bucket", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Observable Up Down Counter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "total_ticket", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Gauge",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "seconds_of_day", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Observable Counter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "events_seen_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Up-Down Counter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    { "expr": "who_knows", "legendFormat": "__auto" }
   ]
  }
 ]
}