# Dusty's docker-compose file
version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: postgres
    volumes:
      - ../TestsRUS/20240212.07.58.45.sql:/docker-entrypoint-initdb.d/initDb.sql
    networks:
      - databaseTunnel
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  blazorapp:
    depends_on:
      - db        # database must build first before blazor app
    build: ..     # builds in the directory ABOVE because that's where the Dockerfile is at
    environment:
      - db=user id=postgres; password=postgres; server=db; database=postgres;
    ports:
      - "7070:8080"   # website will be found at localhost:7070 
    networks:
      - databaseTunnel
    healthcheck:
      test: wget --tries=1 http://localhost:8080/healthcheck || exit 1
      interval: 2s
      retries: 5
      start_period: 5s
      timeout: 2s
    restart: unless-stopped

  blackbox:
    image: prom/blackbox-exporter:v0.23.0
    container_name: blackbox
    restart: unless-stopped
    ports:
      - 9115:9115
    volumes:
     # - /etc/localtime:/etc/localtime:ro
      - ./blackbox/blackbox.yml:/etc/blackbox/blackbox.yml  # change this to use ${PWD}
    command: --config.file=/etc/blackbox/blackbox.yml
    networks:
      otel: # not sure what this does?

  prometheus:
    image: prom/prometheus:v2.43.0
    container_name: prometheus
    hostname: prometheus
    restart: unless-stopped
    ports:
      - 9090:9090
    volumes:
     # - /etc/localtime:/etc/localtime:ro
      - ${PWD}/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml  # change this to use ${PWD}
      - prometheus:/prometheus
    depends_on:
      - blackbox
    networks:
      otel: # not sure what this does...

  grafana:
    image: grafana/grafana:9.4.7
    container_name: grafana
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    volumes:
     # - /etc/localtime:/etc/localtime:ro
      - grafana-data:/var/lib/grafana
      - ${PWD}/grafana/provisioning:/etc/grafana/provisioning
    restart: unless-stopped
    ports:
      - 3000:3000
    depends_on:
      - prometheus
    networks:
      otel: # not sure what this does....

networks:
  databaseTunnel:
    driver: bridge
  otel:

volumes:
  prometheus:
  grafana-data:
