scrape_configs:
  - job_name: 'blackbox'
    scrape_interval: 5s
    metrics_path: /probe
    params:
      module: [http_2xx] # look for response code 200
    static_configs:
      - targets:
        - http://host.docker.internal:5213/healthCheck   # port is from web app launchSettings.json; API endpoint in Program.cs
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115

      