name: backup database
on: 
  - workflow_dispatch
jobs:
  backup:
    runs-on: ethan
    steps:
      - name: backup
        run: |
          mkdir -p /home/ethane/dumps
          CONTAINER_NAME=$(kubectl -n ethan get pods --no-headers -o custom-columns=":metadata.name" | grep blazor-web-db-deployment)
          kubectl -n ethan exec -t $CONTAINER_NAME -- \
            pg_dumpall -c -U postgres \
            > /home/ethane/dumps/ticketsdump.sql