name: Dustys Github Action Workflow
run-name: Dusty's Gitub Action Workflow 🛸
on: [push]
jobs:
  Dusty-Deploy-Pipeline:
    runs-on: dusty
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      
      - run: |
          git clone "https://${{ secrets.DS_ACCESS_TOKEN }}@github.com/SnowSE/ticketsrus-dusty-mustafa-ethan"
          cd MobileApp/dscompose
          docker compose up --build -d
          docker compose down -v
      - uses: actions/checkout@master
      - name: Microsoft Teams Notification
        uses: skitionek/notify-microsoft-teams@master
        if: failure()
        with:
          webhook_url: ${{ secrets.DUSTY_WEBHOOK }}
          overwrite: "{title: `Dusty's Runner Failed`}"
  
