name: Ethan's Deploy Thingy
on: [push]
jobs:
  DeployingPipeline:
    runs-on: ethan
    steps:
      - name: "Stop old compose"
        run: |
            cd ./ticketsrus-dusty-mustafa-ethan/MobileApp/EthansDockerFiles
            docker compose down -v 
            cd ../../../ 
            rm -rf ./ticketsrus-dusty-mustafa-ethan/ 
        working-directory: ./../../../../
      - name: "Clone repo"
        run: | 
            git clone https://${{secrets.NOTGITHUB_PAT}}@github.com/emcbem/ticketsrus-dusty-mustafa-ethan.git
        working-directory: ./../../../../
      - name: "Lint and Build Warnings"
        run: |
            docker run -i --rm -v $(pwd):/app -w /app/TicketWebApp mcr.microsoft.com/dotnet/sdk:8.0 dotnet format --verify-no-changes --no-restore
        working-directory: ./../../../../ticketsrus-dusty-mustafa-ethan/MobileApp/
      - name: "Run docker-compose up"
        id: compose
        run: |
            docker compose up --build -d
        working-directory: ./../../../../ticketsrus-dusty-mustafa-ethan/MobileApp/EthansDockerFiles/
      - name: Microsoft Teams Notification
        uses: skitionek/notify-microsoft-teams@master
        if: failure()
        with:
          webhook_url: ${{ secrets.TEAMS_WEBHOOK }}
          overwrite: "{title: `Ethan's Runner failed! Point and laugh. ${workflow_link}`}"
      - name: Microsoft Teams Notification
        uses: skitionek/notify-microsoft-teams@master
        if: steps.compose.outcome == 'success'
        with:
          webhook_url: ${{ secrets.TEAMS_WEBHOOK }}