name: Ethan's Deploy Thingy
on: [push]
jobs:
  DeployingPipeline:
    runs-on: ethan
    steps:
      - name: "Stop old compose"
        run: |
            docker compose down -v
            cd ../../../
            rm -rf ./ticketsrus-dusty-mustafa-ethan/
        working-directory: ./../../../../ticketsrus-dusty-mustafa-ethan/MobileApp/EthansDockerFiles/
      - name: "Clone repo"
        run: | 
            git clone https://${{secrets.NOTGITHUB_PAT}}@github.com/SnowSE/ticketsrus-dusty-mustafa-ethan.git
        working-directory: ./../../../../
      - name: "Run docker-compose up"
        id: compose
        run: |
            docker compose up --build -d
        working-directory: ./../../../../ticketsrus-dusty-mustafa-ethan/MobileApp/EthansDockerFiles/
      - name: Microsoft Teams Notification
        uses: skitionek/notify-microsoft-teams@master
        if: failure()
        with:
          webhook_url: ${{ secrets.TEAMS_WEBHOOK }}
          overwrite: "{title: `Ethan's Runner failed! Point and laugh. ${workflow_link}`}"
      - name: Microsoft Teams Notification
        uses: skitionek/notify-microsoft-teams@master
        if: steps.compose.outcome == 'success'
        with:
          webhook_url: ${{ secrets.TEAMS_WEBHOOK }}