{
 "title": "Log grafanas",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Ethans buying ticket warn",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{exporter=\"OTLP\"} | json |~ \".*Another Ethan has purchaed a ticket.*\""
    }
   ]
  },
  {
   "title": "Getting Events log",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{exporter=\"OTLP\"} | json | line_format \"{{.attributes_Description}}\" |~ \".*Getting all the events.*\" "
    }
   ]
  },
  {
   "title": "Getting All Tickets Log",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "  {exporter=\"OTLP\"} | json |~ \"All the tickets were got at\""
    }
   ]
  },
  {
   "title": "Add Ticket logs",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "{exporter=\"OTLP\"} | json | line_format \"{{.body}}\" |~ \".*Ticket Service.*\" "
    }
   ]
  },
  {
   "title": "Sending An Email Log",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "{exporter=\"OTLP\"} | json |~ \".*An email was successfully sent.*\""
    }
   ]
  }
 ]
}